In [1]:
import pandas as pd

In [2]:
data = pd.DataFrame({'id':[11,12,13,14,15,16,17,18,19,20],'age':[15,20,25,26,37,31,49,0,0,28],'gender':['M','F','F','M','M','M','F','M','M','F'],'occupation':['Salesman','Doctor','Manager','Teacher','Mechanic','Lawyer','Nurse','Police','Hr','Accountant']})

In [3]:
data

   id  age gender  occupation
0  11   15      M    Salesman
1  12   20      F      Doctor
2  13   25      F     Manager
3  14   26      M     Teacher
4  15   37      M    Mechanic
5  16   31      M      Lawyer
6  17   49      F       Nurse
7  18    0      M      Police
8  19    0      M          Hr
9  20   28      F  Accountant

In [4]:
#Writing to CSV File
data.to_csv('data.csv')

In [5]:
#Reading the CSV File
df = pd.read_csv('data.csv')
df

   Unnamed: 0  id  age gender  occupation
0           0  11   15      M    Salesman
1           1  12   20      F      Doctor
2           2  13   25      F     Manager
3           3  14   26      M     Teacher
4           4  15   37      M    Mechanic
5           5  16   31      M      Lawyer
6           6  17   49      F       Nurse
7           7  18    0      M      Police
8           8  19    0      M          Hr
9           9  20   28      F  Accountant

In [6]:
#Writing to Excel File
data.to_excel('data2.xlsx')

In [7]:
#Reading the Excel File
df2 = pd.read_excel('data2.xlsx')
df2

   id  age gender  occupation
0  11   15      M    Salesman
1  12   20      F      Doctor
2  13   25      F     Manager
3  14   26      M     Teacher
4  15   37      M    Mechanic
5  16   31      M      Lawyer
6  17   49      F       Nurse
7  18    0      M      Police
8  19    0      M          Hr
9  20   28      F  Accountant

In [8]:
#Extracting particular columns from the data set
df = pd.read_csv('data.csv',usecols=['id','occupation'])
df

   id  occupation
0  11    Salesman
1  12      Doctor
2  13     Manager
3  14     Teacher
4  15    Mechanic
5  16      Lawyer
6  17       Nurse
7  18      Police
8  19          Hr
9  20  Accountant