In [78]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

In [79]:
#Load Dataset
data = pd.read_csv("STUD.csv")

In [80]:
print("Original Dataset:\n")
print(data)

Original Dataset:

        NAME   AGE  GENDER  MARKS       CITY
0      VIRAT  18.0    MALE   99.0  BENGALURU
1      ROHIT  19.0    MALE   98.0  MANGALURU
2     DHAWAN  20.0    MALE   96.0        NaN
3     WARNER   NaN    MALE   45.0  MANGALURU
4      GAYLE  14.0    MALE   12.0  BENGALURU
5        ABD  12.0    MALE   23.0        NaN
6    MAXWELL  21.0    MALE    NaN     MYSORE
7       LARA   NaN  FEMALE   34.0        NaN
8    KULDEEP  21.0    MALE    NaN     MYSORE
9     BUMRAH   NaN    MALE   45.0        NaN
10  ARSHDEEP  20.0    MALE   56.0  BENGALURU
11    MILLER   NaN  FEMALE    NaN        NaN
12      SALT  16.0  FEMALE   67.0     MYSORE
13    KRUNAL  15.0    MALE   65.0  MANGALURU
14    HARDIK  13.0    MALE   34.0  BENGALURU
15     SURYA  13.0  FEMALE    NaN        NaN
16    HARMAN   NaN  FEMALE   23.0  BENGALURU
17     SANJU  20.0    MALE   45.0        NaN
18    RASHID  20.0    MALE    NaN    CHENNAI
19    SMRITI  19.0  FEMALE   56.0    CHENNAI
20     VARUN   NaN    MALE   78.0    CHENNAI
21     BROCK   NaN  FEMALE   89.0  BENGALURU
22   GUNTHER  11.0  FEMALE    NaN  BENGALURU
23       JEY  10.0    MALE    NaN        NaN
24     JIMMY  10.0    MALE   67.0  MANGALURU

In [81]:
df = pd.DataFrame(data)

In [82]:
df

        NAME   AGE  GENDER  MARKS       CITY
0      VIRAT  18.0    MALE   99.0  BENGALURU
1      ROHIT  19.0    MALE   98.0  MANGALURU
2     DHAWAN  20.0    MALE   96.0        NaN
3     WARNER   NaN    MALE   45.0  MANGALURU
4      GAYLE  14.0    MALE   12.0  BENGALURU
5        ABD  12.0    MALE   23.0        NaN
6    MAXWELL  21.0    MALE    NaN     MYSORE
7       LARA   NaN  FEMALE   34.0        NaN
8    KULDEEP  21.0    MALE    NaN     MYSORE
9     BUMRAH   NaN    MALE   45.0        NaN
10  ARSHDEEP  20.0    MALE   56.0  BENGALURU
11    MILLER   NaN  FEMALE    NaN        NaN
12      SALT  16.0  FEMALE   67.0     MYSORE
13    KRUNAL  15.0    MALE   65.0  MANGALURU
14    HARDIK  13.0    MALE   34.0  BENGALURU
15     SURYA  13.0  FEMALE    NaN        NaN
16    HARMAN   NaN  FEMALE   23.0  BENGALURU
17     SANJU  20.0    MALE   45.0        NaN
18    RASHID  20.0    MALE    NaN    CHENNAI
19    SMRITI  19.0  FEMALE   56.0    CHENNAI
20     VARUN   NaN    MALE   78.0    CHENNAI
21     BROCK   NaN  FEMALE   89.0  BENGALURU
22   GUNTHER  11.0  FEMALE    NaN  BENGALURU
23       JEY  10.0    MALE    NaN        NaN
24     JIMMY  10.0    MALE   67.0  MANGALURU

In [83]:
data.isnull().sum()

NAME      0
AGE       7
GENDER    0
MARKS     7
CITY      8
dtype: int64

In [84]:
df2 = df.copy()

In [85]:
#Shows only the row/column has a missing value
df2[df2.isnull().any(axis=1)]

       NAME   AGE  GENDER  MARKS       CITY
2    DHAWAN  20.0    MALE   96.0        NaN
3    WARNER   NaN    MALE   45.0  MANGALURU
5       ABD  12.0    MALE   23.0        NaN
6   MAXWELL  21.0    MALE    NaN     MYSORE
7      LARA   NaN  FEMALE   34.0        NaN
8   KULDEEP  21.0    MALE    NaN     MYSORE
9    BUMRAH   NaN    MALE   45.0        NaN
11   MILLER   NaN  FEMALE    NaN        NaN
15    SURYA  13.0  FEMALE    NaN        NaN
16   HARMAN   NaN  FEMALE   23.0  BENGALURU
17    SANJU  20.0    MALE   45.0        NaN
18   RASHID  20.0    MALE    NaN    CHENNAI
20    VARUN   NaN    MALE   78.0    CHENNAI
21    BROCK   NaN  FEMALE   89.0  BENGALURU
22  GUNTHER  11.0  FEMALE    NaN  BENGALURU
23      JEY  10.0    MALE    NaN        NaN

In [86]:
#Handling the missing values

#Remove rows with any missing value
df_row_deleted = df.dropna()

print("\nAfter Row Deletion:\n")
print(df_row_deleted)

After Row Deletion:

        NAME   AGE  GENDER  MARKS       CITY
0      VIRAT  18.0    MALE   99.0  BENGALURU
1      ROHIT  19.0    MALE   98.0  MANGALURU
4      GAYLE  14.0    MALE   12.0  BENGALURU
10  ARSHDEEP  20.0    MALE   56.0  BENGALURU
12      SALT  16.0  FEMALE   67.0     MYSORE
13    KRUNAL  15.0    MALE   65.0  MANGALURU
14    HARDIK  13.0    MALE   34.0  BENGALURU
19    SMRITI  19.0  FEMALE   56.0    CHENNAI
24     JIMMY  10.0    MALE   67.0  MANGALURU

In [87]:
df_row_deleted.isnull().sum()

NAME      0
AGE       0
GENDER    0
MARKS     0
CITY      0
dtype: int64

In [88]:
df_column_deleted = df.dropna(axis=1)

print("\nAfter Column Deletion:\n")
print(df_column_deleted)

After Column Deletion:

        NAME  GENDER
0      VIRAT    MALE
1      ROHIT    MALE
2     DHAWAN    MALE
3     WARNER    MALE
4      GAYLE    MALE
5        ABD    MALE
6    MAXWELL    MALE
7       LARA  FEMALE
8    KULDEEP    MALE
9     BUMRAH    MALE
10  ARSHDEEP    MALE
11    MILLER  FEMALE
12      SALT  FEMALE
13    KRUNAL    MALE
14    HARDIK    MALE
15     SURYA  FEMALE
16    HARMAN  FEMALE
17     SANJU    MALE
18    RASHID    MALE
19    SMRITI  FEMALE
20     VARUN    MALE
21     BROCK  FEMALE
22   GUNTHER  FEMALE
23       JEY    MALE
24     JIMMY    MALE

In [89]:
df_column_deleted.isnull().sum()

NAME      0
GENDER    0
dtype: int64

In [90]:
df_mean = df.copy()

df_mean['AGE'].fillna(df_mean['AGE'].mean(),inplace=True)
df_mean['MARKS'].fillna(df_mean['MARKS'].mean(),inplace=True)

print("\nAfter Mean Imputation\n")
print(df_mean)

After Mean Imputation

        NAME        AGE  GENDER      MARKS       CITY
0      VIRAT  18.000000    MALE  99.000000  BENGALURU
1      ROHIT  19.000000    MALE  98.000000  MANGALURU
2     DHAWAN  20.000000    MALE  96.000000        NaN
3     WARNER  16.222222    MALE  45.000000  MANGALURU
4      GAYLE  14.000000    MALE  12.000000  BENGALURU
5        ABD  12.000000    MALE  23.000000        NaN
6    MAXWELL  21.000000    MALE  57.333333     MYSORE
7       LARA  16.222222  FEMALE  34.000000        NaN
8    KULDEEP  21.000000    MALE  57.333333     MYSORE
9     BUMRAH  16.222222    MALE  45.000000        NaN
10  ARSHDEEP  20.000000    MALE  56.000000  BENGALURU
11    MILLER  16.222222  FEMALE  57.333333        NaN
12      SALT  16.000000  FEMALE  67.000000     MYSORE
13    KRUNAL  15.000000    MALE  65.000000  MANGALURU
14    HARDIK  13.000000    MALE  34.000000  BENGALURU
15     SURYA  13.000000  FEMALE  57.333333        NaN
16    HARMAN  16.222222  FEMALE  23.000000  BENGALURU
17     SANJU  20.000000    MALE  45.000000        NaN
18    RASHID  20.000000    MALE  57.333333    CHENNAI
19    SMRITI  19.000000  FEMALE  56.000000    CHENNAI
20     VARUN  16.222222    MALE  78.000000    CHENNAI
21     BROCK  16.222222  FEMALE  89.000000  BENGALURU
22   GUNTHER  11.000000  FEMALE  57.333333  BENGALURU
23       JEY  10.000000    MALE  57.333333        NaN
24     JIMMY  10.000000    MALE  67.000000  MANGALURU

In [91]:
df_median = df.copy()

df_median['AGE'].fillna(df_median['AGE'].median(),inplace=True)
df_median['MARKS'].fillna(df_median['MARKS'].median(),inplace=True)

print("\nAfter Median Imputation\n")
print(df_median)

After Median Imputation

        NAME   AGE  GENDER  MARKS       CITY
0      VIRAT  18.0    MALE   99.0  BENGALURU
1      ROHIT  19.0    MALE   98.0  MANGALURU
2     DHAWAN  20.0    MALE   96.0        NaN
3     WARNER  17.0    MALE   45.0  MANGALURU
4      GAYLE  14.0    MALE   12.0  BENGALURU
5        ABD  12.0    MALE   23.0        NaN
6    MAXWELL  21.0    MALE   56.0     MYSORE
7       LARA  17.0  FEMALE   34.0        NaN
8    KULDEEP  21.0    MALE   56.0     MYSORE
9     BUMRAH  17.0    MALE   45.0        NaN
10  ARSHDEEP  20.0    MALE   56.0  BENGALURU
11    MILLER  17.0  FEMALE   56.0        NaN
12      SALT  16.0  FEMALE   67.0     MYSORE
13    KRUNAL  15.0    MALE   65.0  MANGALURU
14    HARDIK  13.0    MALE   34.0  BENGALURU
15     SURYA  13.0  FEMALE   56.0        NaN
16    HARMAN  17.0  FEMALE   23.0  BENGALURU
17     SANJU  20.0    MALE   45.0        NaN
18    RASHID  20.0    MALE   56.0    CHENNAI
19    SMRITI  19.0  FEMALE   56.0    CHENNAI
20     VARUN  17.0    MALE   78.0    CHENNAI
21     BROCK  17.0  FEMALE   89.0  BENGALURU
22   GUNTHER  11.0  FEMALE   56.0  BENGALURU
23       JEY  10.0    MALE   56.0        NaN
24     JIMMY  10.0    MALE   67.0  MANGALURU

In [96]:
df_mode = df.copy()

df_mode['CITY'].fillna(df_mode['CITY'].mode()[0],inplace=True)
df_mode['GENDER'].fillna(df_mode['GENDER'].mode()[0],inplace=True)
df_mode['AGE'].fillna(df_mode['AGE'].mode()[0],inplace=True)
df_mode['MARKS'].fillna(df_mode['MARKS'].mode()[0],inplace=True)

print("After Mode Imputation:\n")
print(df_mode)

After Mode Imputation:

        NAME   AGE  GENDER  MARKS       CITY
0      VIRAT  18.0    MALE   99.0  BENGALURU
1      ROHIT  19.0    MALE   98.0  MANGALURU
2     DHAWAN  20.0    MALE   96.0  BENGALURU
3     WARNER  20.0    MALE   45.0  MANGALURU
4      GAYLE  14.0    MALE   12.0  BENGALURU
5        ABD  12.0    MALE   23.0  BENGALURU
6    MAXWELL  21.0    MALE   45.0     MYSORE
7       LARA  20.0  FEMALE   34.0  BENGALURU
8    KULDEEP  21.0    MALE   45.0     MYSORE
9     BUMRAH  20.0    MALE   45.0  BENGALURU
10  ARSHDEEP  20.0    MALE   56.0  BENGALURU
11    MILLER  20.0  FEMALE   45.0  BENGALURU
12      SALT  16.0  FEMALE   67.0     MYSORE
13    KRUNAL  15.0    MALE   65.0  MANGALURU
14    HARDIK  13.0    MALE   34.0  BENGALURU
15     SURYA  13.0  FEMALE   45.0  BENGALURU
16    HARMAN  20.0  FEMALE   23.0  BENGALURU
17     SANJU  20.0    MALE   45.0  BENGALURU
18    RASHID  20.0    MALE   45.0    CHENNAI
19    SMRITI  19.0  FEMALE   56.0    CHENNAI
20     VARUN  20.0    MALE   78.0    CHENNAI
21     BROCK  20.0  FEMALE   89.0  BENGALURU
22   GUNTHER  11.0  FEMALE   45.0  BENGALURU
23       JEY  10.0    MALE   45.0  BENGALURU
24     JIMMY  10.0    MALE   67.0  MANGALURU

In [97]:
#Encoding Categorical Data(Gender & City)

#Label Encoding
le = LabelEncoder()
df_mode['GENDER'] = le.fit_transform(df_mode['GENDER'].astype(str))
df_mode['CITY'] = le.fit_transform(df_mode['CITY'].astype(str))

print("\nAfter Encoding Categorical Data:\n ")
print(df_mode)

After Encoding Categorical Data:

        NAME   AGE  GENDER  MARKS  CITY
0      VIRAT  18.0       1   99.0     0
1      ROHIT  19.0       1   98.0     2
2     DHAWAN  20.0       1   96.0     0
3     WARNER  20.0       1   45.0     2
4      GAYLE  14.0       1   12.0     0
5        ABD  12.0       1   23.0     0
6    MAXWELL  21.0       1   45.0     3
7       LARA  20.0       0   34.0     0
8    KULDEEP  21.0       1   45.0     3
9     BUMRAH  20.0       1   45.0     0
10  ARSHDEEP  20.0       1   56.0     0
11    MILLER  20.0       0   45.0     0
12      SALT  16.0       0   67.0     3
13    KRUNAL  15.0       1   65.0     2
14    HARDIK  13.0       1   34.0     0
15     SURYA  13.0       0   45.0     0
16    HARMAN  20.0       0   23.0     0
17     SANJU  20.0       1   45.0     0
18    RASHID  20.0       1   45.0     1
19    SMRITI  19.0       0   56.0     1
20     VARUN  20.0       1   78.0     1
21     BROCK  20.0       0   89.0     0
22   GUNTHER  11.0       0   45.0     0
23       JEY  10.0       1   45.0     0
24     JIMMY  10.0       1   67.0     2

In [98]:
#Feature Scaling (Normalization)
scaler = MinMaxScaler()

In [99]:
#Scaling Age and Marks columns
df_mode[['AGE','MARKS']] = scaler.fit_transform(df_mode[['AGE','MARKS']])

In [100]:
print("After Normalization\n")
print(df_mode)

After Normalization

        NAME       AGE  GENDER     MARKS  CITY
0      VIRAT  0.727273       1  1.000000     0
1      ROHIT  0.818182       1  0.988506     2
2     DHAWAN  0.909091       1  0.965517     0
3     WARNER  0.909091       1  0.379310     2
4      GAYLE  0.363636       1  0.000000     0
5        ABD  0.181818       1  0.126437     0
6    MAXWELL  1.000000       1  0.379310     3
7       LARA  0.909091       0  0.252874     0
8    KULDEEP  1.000000       1  0.379310     3
9     BUMRAH  0.909091       1  0.379310     0
10  ARSHDEEP  0.909091       1  0.505747     0
11    MILLER  0.909091       0  0.379310     0
12      SALT  0.545455       0  0.632184     3
13    KRUNAL  0.454545       1  0.609195     2
14    HARDIK  0.272727       1  0.252874     0
15     SURYA  0.272727       0  0.379310     0
16    HARMAN  0.909091       0  0.126437     0
17     SANJU  0.909091       1  0.379310     0
18    RASHID  0.909091       1  0.379310     1
19    SMRITI  0.818182       0  0.505747     1
20     VARUN  0.909091       1  0.758621     1
21     BROCK  0.909091       0  0.885057     0
22   GUNTHER  0.090909       0  0.379310     0
23       JEY  0.000000       1  0.379310     0
24     JIMMY  0.000000       1  0.632184     2

In [103]:
#Split datasets into features and target
#Suppose we predict Marks
X = df_mode[['AGE','GENDER','CITY']]
Y = df_mode['MARKS']

In [104]:
#Train-Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

print("\nTraining Data:\n",X_train)
print("\nTesting Data:\n",X_test)

Training Data:
          AGE  GENDER  CITY
22  0.090909       0     0
17  0.909091       1     0
24  0.000000       1     2
23  0.000000       1     0
14  0.272727       1     0
1   0.818182       1     2
10  0.909091       1     0
13  0.454545       1     2
8   1.000000       1     3
6   1.000000       1     3
18  0.909091       1     1
4   0.363636       1     0
9   0.909091       1     0
7   0.909091       0     0
20  0.909091       1     1
3   0.909091       1     2
0   0.727273       1     0
21  0.909091       0     0
15  0.272727       0     0
12  0.545455       0     3

Testing Data:
          AGE  GENDER  CITY
5   0.181818       1     0
2   0.909091       1     0
19  0.818182       0     1
16  0.909091       0     0
11  0.909091       0     0